### ISSUE TITLE
Error message on revampt-on-social-logins branch

### ISSUE THREAD

**Issue by dantesolis** [dantesolis/gifmemore#7]
```shell
/Users/DS/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined local variable or method `authorization' for User (call 'User.connection' to establish a connection):Class (NameError)
	from /Users/DS/Projects/gifmemore/app/models/user.rb:50:in `<class:User>'
	from /Users/DS/Projects/gifmemore/app/models/user.rb:1:in `<top (required)>'
```

**Comment by dantesolis** [comment]
Able to sign in with Facebook login development.
